# Generated by Django 3.2 on 2022-11-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Form Messages'},
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_to',
            field=models.BooleanField(default=False),
        ),
    ]
