# Generated by Django 3.2 on 2022-11-23 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20221123_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply_sent', models.TextField()),
                ('related_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_message', to='contact.contact')),
            ],
            options={
                'verbose_name_plural': 'Contact Form Notes',
            },
        ),
    ]
