# Generated by Django 3.2 on 2022-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnotes',
            name='replied_to',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Replied?'),
        ),
    ]
