# Generated by Django 3.2 on 2022-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_ordernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotes',
            name='order_fulfilled',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Fulfilled?'),
        ),
    ]
