# Generated by Django 3.2 on 2022-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0008_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Awful'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('approved', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
