# Generated by Django 3.2 on 2022-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221028_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
