# Generated by Django 3.2 on 2022-11-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
