# Generated by Django 3.2 on 2022-11-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20221115_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Genre Categories',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='FormatCategory',
        ),
        migrations.AlterModelOptions(
            name='formatcategory',
            options={'verbose_name_plural': 'Format Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='format_category',
        ),
        migrations.AddField(
            model_name='product',
            name='genre_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.genrecategory'),
        ),
    ]
