# Generated by Django 3.2 on 2022-11-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20221118_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='genre_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='format_category',
        ),
        migrations.DeleteModel(
            name='FormatCategory',
        ),
    ]
