# Generated by Django 3.2 on 2022-11-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20221118_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Format'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='format',
        ),
    ]
