# Generated by Django 3.2 on 2022-11-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20221118_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='format',
            new_name='category',
        ),
    ]
