# Generated by Django 3.2 on 2022-11-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_format_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Formats'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
    ]
