# Generated by Django 3.2 on 2022-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['?']},
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
