# Generated by Django 3.2 on 2022-11-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20221123_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Format',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='format',
        ),
    ]
