# Generated by Django 3.2 on 2022-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20221124_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
